version: '3.5'

services:
  worker-0:
    restart: always
    image: pilotcodiml/pilotcodi
    command: serve --model PilotCodiML/StarCoder-1B --device cuda --no-webserver
    volumes:
      - "$HOME/.pilotcodi:/data"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  worker-1:
    restart: always
    image: pilotcodiml/pilotcodi
    command: serve --model PilotCodiML/StarCoder-1B --device cuda --no-webserver
    volumes:
      - "$HOME/.pilotcodi:/data"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

  web:
    image: caddy
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
    ports:
      - "8080:8080"
