apiVersion: v2
name: codibase
version: ${buildVersion}
description: All-In-One DevOps Platform
type: application
keywords:
  - codibase
  - devops
  - vcs
  - cicd
home: https://codibase.io
maintainers:
  - name: Robin Shen
    email:  robin@codibase.io
  - name: Abdul Khaliq
    email: a.khaliq@outlook.my
appVersion: ${buildVersion}
