apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ods.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.codibase.initSettings.password }}
  password: {{ .Values.codibase.initSettings.password | b64enc }}
{{- end }}
  dbPassword: {{ .Values.database.password | b64enc }}
