services:
  codibase:
    image: 1dev/server
    volumes:
      - ./codibase:/opt/codibase
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "6610:6610"
      - "6611:6611"
    environment:
      ### This should be the same as POSTGRES_PASSWORD env below
      hibernate_connection_password: "changeit"

      hibernate_dialect: io.codibase.server.persistence.PostgreSQLDialect
      hibernate_connection_driver_class: org.postgresql.Driver
      hibernate_connection_url: jdbc:postgresql://postgres:5432/codibase
      hibernate_connection_username: postgres
    tty: true
    depends_on:
      - "postgres"

  postgres:
    image: postgres:14-alpine3.15
    restart: always
    environment:
      ### Change this
      POSTGRES_PASSWORD: "changeit"

      POSTGRES_USER: "postgres"
      POSTGRES_DB: "codibase"
    expose:
      - "5432"
    volumes:
      - ./codibase/site/postgres:/var/lib/postgresql/data
